# NUMPY

## CREATION OF ARRAY

Numpy is a library from python used for working with arrays , it is a short term for numerical python.

In [1]:
import numpy as np

For creation of arrays we use alias_name.array()

In [4]:
arr = np.array([1,2,3,4,5])
print(arr)

[1 2 3 4 5]


For creation of array between a specific range we use arange function (last value is exluded) . 


In [5]:
arr = np.arange(5,10)
print(arr)

[5 6 7 8 9]


Linspace - It is used for creating a array to provide elements in a range with equal spacings.
Format - .linpace(n,m,x) { n = initial value , m = final value , x = number of elements}.

In [28]:
arr = np.linspace(1,100,10)
arr2 = arr.astype(int)
print(arr2)

[  1  12  23  34  45  56  67  78  89 100]


For creating a array or matrix with entries 0 and 1 we use .zeros(for zero) and .ones(for one) and .eye(for an identity matrix).

In [32]:
arr_Zer = np.zeros((2,2))

In [33]:
arr_One = np.ones((2,3))

In [34]:
arr_iden = np.eye(5)

In [35]:
print(arr_Zer.astype(int))

[[0 0]
 [0 0]]


In [36]:
print(arr_One.astype(int))

[[1 1 1]
 [1 1 1]]


In [37]:
print(arr_iden.astype(int))

[[1 0 0 0 0]
 [0 1 0 0 0]
 [0 0 1 0 0]
 [0 0 0 1 0]
 [0 0 0 0 1]]


## INDEXING AND SLICING

Simple Indexing - It is used to access the element of an array by giving the element's index.

In [50]:
Sim = np.arange(10)
print(Sim)

[0 1 2 3 4 5 6 7 8 9]


In [51]:
print(Sim[3])

3


Slicing - It defines a range in which we want to get the elements , and the last one is exclusive.

In [52]:
print(Sim[0:4])

[0 1 2 3]


Stride - We use this type of slicing to get a step between the ranges . format = [start:end:Step] and if we use -1 as Step it access the elements from last and prints it .  

In [55]:
print(Sim[::2])

[0 2 4 6 8]


In [56]:
print(Sim[::-1])

[9 8 7 6 5 4 3 2 1 0]


In [57]:
print(Sim[::-2])

[9 7 5 3 1]


We can also access the elements by row and column in a matrix.

In [66]:
mat = np.array([[1,2,3,4],[4,5,6,5],[7,8,9,6]])
print(mat)

[[1 2 3 4]
 [4 5 6 5]
 [7 8 9 6]]


So here we can see i have accessed a sub matrix by using a specific format i.e mat[row_index:row_index1 , col_index:col_index1]

In [75]:
print(mat[0:2,1:3])

[[2 3]
 [5 6]]


## SHAPE MANIPULATION

reshape(newshape) – Change array shape.

flatten() – Collapse multi-dim array to 1D.

transpose() – Flip rows and columns.

In [3]:
art = np.arange(1,17)
print(art)

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16]


In [5]:
art_new = art.reshape(4,4)
print(art_new)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]


In [8]:
art_flat = art_new.flatten()
print(art_flat)

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16]


In [10]:
art_trans = art_new.T
print(art_trans)

[[ 1  5  9 13]
 [ 2  6 10 14]
 [ 3  7 11 15]
 [ 4  8 12 16]]


# MATH OPERATION

Math Operations

mean() – Mean of array.

std() – Standard deviation.

sum() – Total sum of elements.

dot() – Dot product (vector/matrix).

matmul() – Matrix multiplication.

In [11]:
arr_math = np.arange(1,17)
print(arr_math)

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16]


In [12]:
print(arr_math.mean())
print(arr_math.std())
print(arr_math.sum())

8.5
4.6097722286464435
136


In [13]:
vec1 = np.array([1,2,3])
vec2 = np.array([4,5,6])
print(np.dot(vec1,vec2))

32


In [15]:
A = np.array([[1,2],[4,5]])
B = np.array([[7,8],[9,10]])
print(np.matmul(A,B))

[[25 28]
 [73 82]]


# Random Functions

In [16]:
from numpy import random

rand() – Uniform random floats in.

randn() – Standard normal distribution (mean=0, std=1).

randint() – Random integers in specified range.

choice() – Random selection from an array.

In [23]:
rnd_arr = random.rand(2)
print(rnd_arr)

[0.05558034 0.4882731 ]


In [24]:
rndn_arr = random.randn(2)
print(rndn_arr)

[ 1.2794488 -0.6435653]


In [34]:
rndint_arr = random.randint(1,10,size=(2,2))
print(rndint_arr)

[[7 2]
 [3 1]]


In [38]:
ch = random.choice([10,20,30],size=(2,2))
print(ch)

[[20 20]
 [10 10]]
